### ISSUE TITLE
Mute mycroft-core while speaking with the application

### ISSUE THREAD

**Issue by noah-be** [MycroftAI/Mycroft-Android#94]
Hello and thank you for your awesome work after 30 minutes I have the working app on my phone now. I had to change a line of code in TTSManager from 
`val result = mTts.setLanguage(Locale.US) `
to 
`val result = mTts.setLanguage(Locale.getDefault()) `
for TTS to be in my mother tongue but now it works. Only thing I am missing is the possibility to mute the mycroft-core voice feedback. If I use the app to talk to mycroft while I am in the same room as my Picroft instance I get voice feedback from my phone and at the same time from picroft. If there is a possibility to implement such a function I would really appreciate it. Anyway thank you for your work I am not really into android app writing but I got it running really quick. Hope I can help in the future with this project and other mycroft related stuff as well.

**Comment by aruke** [comment]
Between the issue opening and today, the mute button appeared in the left bottom corner. It mutes the mobile output so that you can only hear the Mycroft instance.

![device-2020-10-15-083628](https://user-images.githubusercontent.com/7069270/96056556-d92cc900-0ec1-11eb-98b7-9c8763671236.png)

I think the issue can be closed now.

**Comment by noah-be** [comment]
Thank you! Indeed it can be closed.
